### ISSUE TITLE
Revisión de evaluación técnica

### ISSUE THREAD

**Issue by letbrasil** [dymaxionlabs/unetseg#2]
## Issue de revisión de evaluación técnica:

Al haber contrastado la información presentadas en el repo oficial con los campos solicitados en la plantilla de README.md hemos encontrado los siguiente puntos a mejorar:

- [x] Agregar el microservicio de reportes de evaluación estática de código de Sonarcloud, teniendo en cuenta que las condiciones ideales de los reportes son:

      1 Ausencia de fallos estructurales
      2 Menos del 25% de líneas duplicadas
      3 Menos de 10 problemas críticos
      4 Más del 50% de clases, interfaces y métodos documentados
      5 Deuda técnica menor a 30 días
      6 Cobertura de test más del 25%
      
      Esto se valida automáticamente cuando corre el reporte del último commit del repositorio.
      
- [x] Agregar el badge en markdown de este servicio visible en el readme.md.

- [ ] Agregar un microservicio de integración continua de código, recomendamos Travis CI (opcional).

- [ ] Agregar el badge del microservicio de integración continua de código visible en el readme.md. El build debe estar en estado passing (opcional).

- [ ] Actualizar versión de todas las dependencias.

**Comment by letbrasil** [comment]
@munshkr Es posible vincular este repositório con [Sonarcloud](https://sonarcloud.io/)?

**Comment by munshkr** [comment]
@letbrasil sí es posible, lo hemos hecho en otro repositorio (ideuy-py), ahí creo que lo agregué: https://sonarcloud.io/dashboard?id=dymaxionlabs_unetseg  necesitan acceso para configurar algo?

**Comment by letbrasil** [comment]
@munshkr Gracias, ahora ya tenemos el badge! 🎉
[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=dymaxionlabs_unetseg&metric=alert_status)](https://sonarcloud.io/dashboard?id=dymaxionlabs_unetseg)
Pero parece que se necesita alguna otra configuración porque se ve como `Quality gate not computed`... Puede tener algo que ver con eso: https://community.sonarsource.com/t/all-new-projects-must-now-define-their-new-code-on-sonarcloud-to-get-a-quality-gate/32864
Podrías verificarlo, por favor?

**Comment by munshkr** [comment]
Ahora sí! había que hacer un commit nuevo para que computara el quality gate.
![image](https://user-images.githubusercontent.com/4862/124467984-f286e580-dd6e-11eb-9ca4-bdc56b43ae6e.png)
